image: debian/testing
packages:
  - emacs
  - rsync
sources:
  - https://git.sr.ht/~bzg/ox-html-timeline
secrets:
  - bdd50953-add5-4ddb-9f34-9f0781900b7e
tasks:
  - publish: |
      cd agenda-tnt
      ./publish.sh
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av agenda-tnt/agenda/* web@code.gouv.fr:/home/web/websites/code.gouv.fr_home/preproduction/agenda-tnt/
triggers:
  - action: email
    condition: failure
    to: ~bzg/org-build-failures@lists.sr.ht
